language: python
python:
- '3.6'
intall: pip install -r requirements.txt
script: echo pass
deploy:
  provider: heroku
  api_key:
    secure: iIUcx+BFdEPiVeFWWdEvn0BNAQARi6n7XbiGsHQto50ukB2YTooDhiq6GiEyHcLeMrrUzfI/AHd8H5uy2gkLbI8VNwTrVEfluyY1ZrOgnVhOFo8gY/Voabi5Mj3ZqQX4drw2U/G3oowXc++S41P30OmOqTkLcg5SwtY6/lwVHSZ4azTY9bEjllTiH5mv7nXBeBJOjRFIzOcr8SOKODzKemgopX+OI3i78u2187WFbFzzKEebJwOn/SViu5rRv+BARuTbos420AU6y/U/DJA63cu50HIU0eLNY8253EX2QgJs1TQsfwoaxXGzX5H3e3zu21t+jfDNnIfaCmAwUan69YCgRTHyI2Nzzt01+JgitrtIPR1JFm4PcueVwSigQFRqt/0P49a5YwuIVbnESQPRBLw6hqUWUhElmPOk0enV4Ty+DiqWcrsBH0d8TFMUGQ3sB0BK/SsBPUFtQojWZ847Sk8SFo9InTLtX2/4X5emf8eHi1KyXfmmLIK69mymxf88yTRWQrRD8l+atOIs+CPPiy3iQdfi+4ZY6rfIW0ptr4stsJdVSOB/Zw69Z9Ez/ImrUYft+AV6AKKlyoda1yvk54HRrIinKOhqkiqdtfqZWPOX4DaKqSKyQYNQfV+tdzO1WwRMgZ3UeiWZUu6L+86pKbyOKWoZvvnVp39f6Jm1fgk=
  app: dc-bikes-map
  skip_cleanup: true
