language: python
python:
- '3.6'
intall: pip install -r requirements.txt
script: echo pass
deploy:
  provider: heroku
  api_key:
    secure: ECU+KeR94gqr0jY+2PBBds1obsA0fjVNKQiHb4bi/A3EdxBpgcbH9nsznp81FiF02cvTZcgy8ah/s5oPpigiyElLveJc6BSVYvcmvv8pfbXiYNCz/uOA+a+BIR/DAxwKhI8xMGvNd6fT00+JwQ+6BPIJdprc1GaNAI7IT2D4hXdmlaAJYnodqX2Zjd7DYAljW9H1AcO7QnJxdkatEgiL84KZmfw2llWWhG+MGsaUg06eSE0+sTxNe0JBCaD8qXbUUjSg+3X53WwqDp0GJZRTsyzCwFnyOnfXt1PJg4tuNjpIosQX+pteJ9zYhQj2yU3ApmREO4GyN8p0YPaPtuSsV/bnk3uTBpJ1DAeeVdoSRnAeS6GgzKqayRQyhoEdoZj/QbuIYoUQjzAnqSwJMFLNwDFaTyD8h/rL3LODHLbUnBYRSI40BjIntA2gVYrC6bKi6PYeWnZHL2M9VItxOAC9ypZ9N5FkjrgWHOjsQ1tIXOpi5gQQ9y2D8ACJnOxGqAkkd7ccnhbNedLswCVYf3upAsUhWnIrT5hCqAcumSUtZq5o3QfMs9sYG1Ol0K0M0i/l4GQYWddVLPLXuXFrZW9aaCfPfy74HfIN6JA8ODJV5fAg6fZeloiflUENsJ8y7ux31Vpu7F0+H6V4csFdh7doo0FS75Um6hnFtElCv7ILj+Q=
  app: dc-bikes-map
  skip_cleanup: true